type TriggerResponse {
  workflow_run_id: uuid!
  status: String!
}

input TriggerInput {
  workflow_id: uuid!
}

type ApproveResponse {
  success: Boolean!
  step_run_id: uuid!
}

input ApproveInput {
  step_run_id: uuid!
}

type WebhookTriggerResponse {
  workflow_run_id: uuid!
  status: String!
}

input WebhookTriggerInput {
  workflow_id: uuid!
  payload: jsonb
}

type Mutation {
  triggerWorkflowRun(input: TriggerInput!): TriggerResponse
  approveStep(input: ApproveInput!): ApproveResponse
  webhookTrigger(input: WebhookTriggerInput!): WebhookTriggerResponse
}
